In [60]:
import torch
import numpy as np

In [61]:
# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5,3)
x

tensor([[5.5830e+15, 4.5738e-41, 5.5830e+15],
        [4.5738e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.5738e-41, 7.7052e+31, 7.2148e+22],
        [2.5226e-18, 6.4825e-10, 1.0527e-11]])

In [62]:
# Construct a randomly initialized matrix:
x = torch.rand(5,3)
x

tensor([[0.7752, 0.3090, 0.0605],
        [0.4849, 0.1752, 0.7421],
        [0.1474, 0.7187, 0.4524],
        [0.7961, 0.7507, 0.8082],
        [0.3004, 0.7665, 0.2301]])

In [63]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [64]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 2])
x

tensor([5.5000, 2.0000])

In [65]:
# or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [66]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 0.0590, -0.3955, -0.8326],
        [ 0.2114,  0.3128,  1.2250],
        [-0.6097, -1.2032,  1.5231],
        [-1.0818, -0.2572,  0.0254],
        [-0.2445,  1.3533, -0.7799]])

In [67]:
x.size()

torch.Size([5, 3])

### Operation

In [68]:
y = torch.rand(5,3)
y

tensor([[0.6254, 0.1045, 0.7915],
        [0.9362, 0.8518, 0.5100],
        [0.7723, 0.9274, 0.4330],
        [0.1969, 0.2699, 0.9571],
        [0.1557, 0.2075, 0.8380]])

In [69]:
# Addition: syntax 1
x+y

tensor([[ 0.6845, -0.2911, -0.0411],
        [ 1.1476,  1.1647,  1.7350],
        [ 0.1626, -0.2758,  1.9561],
        [-0.8848,  0.0126,  0.9825],
        [-0.0888,  1.5608,  0.0580]])

In [70]:
# Addition: syntax 2
torch.add(x, y)

tensor([[ 0.6845, -0.2911, -0.0411],
        [ 1.1476,  1.1647,  1.7350],
        [ 0.1626, -0.2758,  1.9561],
        [-0.8848,  0.0126,  0.9825],
        [-0.0888,  1.5608,  0.0580]])

In [71]:
# Addition: providing an output tensor as argument
result = torch.empty(5,3)
torch.add(x,y, out=result)
result

tensor([[ 0.6845, -0.2911, -0.0411],
        [ 1.1476,  1.1647,  1.7350],
        [ 0.1626, -0.2758,  1.9561],
        [-0.8848,  0.0126,  0.9825],
        [-0.0888,  1.5608,  0.0580]])

In [72]:
# # adds x to y
y.add_(x)
y

tensor([[ 0.6845, -0.2911, -0.0411],
        [ 1.1476,  1.1647,  1.7350],
        [ 0.1626, -0.2758,  1.9561],
        [-0.8848,  0.0126,  0.9825],
        [-0.0888,  1.5608,  0.0580]])

In [73]:
# You can use standard NumPy-like indexing with all bells and whistles!
x

tensor([[ 0.0590, -0.3955, -0.8326],
        [ 0.2114,  0.3128,  1.2250],
        [-0.6097, -1.2032,  1.5231],
        [-1.0818, -0.2572,  0.0254],
        [-0.2445,  1.3533, -0.7799]])

In [74]:
x[:,1]

tensor([-0.3955,  0.3128, -1.2032, -0.2572,  1.3533])

In [75]:
# Resizing: If you want to resize/reshape tensor, you can use 
x = torch.randn(4,4)
x

tensor([[ 0.0684, -1.0427,  0.7234, -1.8044],
        [ 0.6347, -0.2675,  0.5920, -1.1908],
        [-1.5069,  0.2455,  0.5426, -1.7711],
        [-0.3767,  0.1849, -0.3886, -0.3468]])

In [76]:
y = x.view(16)
y

tensor([ 0.0684, -1.0427,  0.7234, -1.8044,  0.6347, -0.2675,  0.5920, -1.1908,
        -1.5069,  0.2455,  0.5426, -1.7711, -0.3767,  0.1849, -0.3886, -0.3468])

In [77]:
z = x.view(-1, 8)
z

tensor([[ 0.0684, -1.0427,  0.7234, -1.8044,  0.6347, -0.2675,  0.5920, -1.1908],
        [-1.5069,  0.2455,  0.5426, -1.7711, -0.3767,  0.1849, -0.3886, -0.3468]])

In [78]:
print(x.shape, y.shape, z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [79]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2329])
-0.23285067081451416


### numpy

In [80]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [81]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [82]:
# See how the numpy array changed in value.
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [83]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

### Converting NumPy Array to Torch Tensor

In [84]:
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [85]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

In [86]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [87]:
# cuda is not install on my pc for this this will not work
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu', torch.double))
    

### Autograd: Automatic Differentiation

In [88]:
# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [89]:
# Do a tensor operation:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [90]:
# y was created as a result of an operation, so it has a grad_fn.
y.grad_fn

In [91]:
# Do more operations on y
z = y*y*3
z


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [92]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [93]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.
a = torch.randn(2,2)
a = ((a*3)/ (a-1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


### Gradients

Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.)).

In [94]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [100]:
x = torch.randn(3, requires_grad=True)
x


tensor([0.0037, 0.5468, 0.3842], requires_grad=True)

In [101]:
y = x*2
y

tensor([0.0074, 1.0937, 0.7685], grad_fn=<MulBackward0>)

In [102]:
while y.data.norm() < 1000:
    y = y*2
    
print(y)

tensor([   7.5463, 1119.9240,  786.9039], grad_fn=<MulBackward0>)


In [103]:
# Now in this case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly, but if we just want the vector-Jacobian product, simply pass the vector to backward as argument:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [104]:
# You can also stop autograd from tracking history on Tensors with .requires_grad=True either by wrapping the code block in with torch.no_grad():
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)


True
True
False


In [105]:
# Or by using .detach() to get a new Tensor with the same content but that does not require gradients:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())


True
False
tensor(True)
